### ISSUE TITLE
Where does it get the songs from?

### ISSUE THREAD

**Issue by roshin8** [AllToMP3/alltomp3-app#11]
Noob here. Can't find in the source code where you get the songs from once the spotify playlist is added.

**Comment by NTag** [comment]
The function [downloadPlaylistWithTitles](https://github.com/AllToMP3/alltomp3/blob/master/index.js#L1916) will be called with the URL of the Spotify playlist, it will get the titles of all songs in the playlist through Spotify's API, and then it will search every song on YouTube with the function [videoForSong](https://github.com/AllToMP3/alltomp3/blob/master/index.js#L1400).

To sum up, songs are not downloaded directly from Spotify, but from YouTube.

**Comment by roshin8** [comment]
At what quality is the audio being downloaded at? 320kbps?

**Comment by NTag** [comment]
The quality depends on the YouTube video found, it is 128 kb/S, 192 kb/s or 256 kb/s.

**Comment by clay53** [comment]
Is it possible to make sure the youtube video & the length of the song on Spotify match? A bunch of the songs on my playlist that were downloaded do not match the ones on Spotify.

**Comment by NTag** [comment]
The algorithm tries to find the best video, using its title, number of views, likes, dislikes, and **duration**. But it doesn't always find the right video.
