### ISSUE TITLE
YouTube downloads only progressing to about 1%

### ISSUE THREAD

**Issue by SuperNunb** [AllToMP3/alltomp3-app#122]
- Windows 10
- Newest version, I believe; I don't really know where to find the version
- I'm trying to download a bunch of different YouTube videos
- Each video is being recognized, and the progress bar goes to about 1% on each song, but never goes any further. 
- I believe this issue has occurred before, but had been fixed, and is somehow happening again.  
- I have also tried turning off antivirus, but to no avail. 

![image](https://user-images.githubusercontent.com/33640719/59609894-e7a47e00-90dd-11e9-85ca-4823c766964b.png)

**Comment by bonzibuddyXP** [comment]
me too

**Comment by onetoomanyonesandzeroes** [comment]
happens for me as well

**Comment by mojjj** [comment]
does the download target directory exist? what you describe happened for me when the target dir was no longer in place (i moved it)

**Comment by SuperNunb** [comment]
Yeah; the program seems to be updating right now though, so maybe that will fix it,

**Comment by onetoomanyonesandzeroes** [comment]
Since this program uses anyway another work: youtube-dl for which is just a GUI and not even working I have honestly no use for it as the said program works with no fuss no complaints. I recommend youtube-dl.exe as solution.

**Comment by SuperNunb** [comment]
😃 It works now, after the most recent update. Sometimes you just have to wait.
