### ISSUE TITLE
Downloading stops

### ISSUE THREAD

**Issue by SkylordBrebro** [AllToMP3/alltomp3-app#129]
* My operating system is: Windows;
* My AllToMP3 version is: 0.3.11;
* Playlist that I'm trying to download: https://open.spotify.com/playlist/6EwBcohwBJe5QMPsHZQ5uW?si=xMnN_CigRaOty-9VqC58bw;
* What my problem is: If I try to  download a big playlist after a few songs it just stops. I've tried two playlists and one of them stopped of 4 songs and this one stopped at 10. I don't have anything preventing the program from doing what it should yet it stops.
If there is a way to fix this please let me know. I'll be sending a message using the program if that help at all (red another bug report where they were told to do so).
Other than the program stopping, as far as I can tell, it works very well!

**Comment by SkylordBrebro** [comment]
![37e452313854e32c48f8bd64858a4746](https://user-images.githubusercontent.com/46985701/63114454-ddc6bc00-bf62-11e9-85fb-430663e91da9.png)

**Comment by TanguyOrtegat** [comment]
got same problem, having a private playlist with 184 songs and stops after 27 songs
