### ISSUE TITLE
AllToMp3 doesn't download songs from Spotify

### ISSUE THREAD

**Issue by Auranna07** [AllToMP3/alltomp3-app#143]
Hi! I started to use this program from 2018 and It does work with my laptop, but when I purchased this new pc It doesn't download.

My system operator is:
-Windows 10 pro

-My version of AllToMp3 is:
-AllToMP3 (0.3.11)

-The songs are:
https://open.spotify.com/track/4EivmOT13NMpNSfTKn9p4s?si=lBScAjQcQ2KVvuvjf8bKCw
https://open.spotify.com/track/2MvvoeRt8NcOXWESkxWn3g?si=amFA7kNSSpqTtMXoPY66hg
https://open.spotify.com/track/5mu1uv8RmzDkF8foePK5qa?si=0Mr3nb2FTWeWUpqrfXbI_w
https://open.spotify.com/track/2qxmye6gAegTMjLKEBoR3d?si=AUjVhNOwThqF7mYd67TrKg

And I think that I couldn't download any type of song...

(https://user-images.githubusercontent.com/60031477/72661790-e6726100-39de-11ea-8f2f-85f160cb6975.png)

**Comment by 3Domse3** [comment]
I have the same problem :/

**Comment by Cristobal65** [comment]
+ 1

**Comment by TomDoughens** [comment]
yep, same here. Think its to do with Spotify's new privacy policy. Really hope the devs will update the program.

**Comment by tojwek123** [comment]
Check my comment: https://github.com/AllToMP3/alltomp3-app/issues/142#issuecomment-576027297

Apparently updating 'youtube-dl' binary fixes the problem (at least on Windows 10).

**Comment by Auranna07** [comment]
> Check my comment: [#142 (comment)](https://github.com/AllToMP3/alltomp3-app/issues/142#issuecomment-576027297)
> 
> Apparently updating 'youtube-dl' binary fixes the problem (at least on Windows 10).

Thanks man! It all worked <3

**Comment by TomDoughens** [comment]
> Check my comment: [#142 (comment)](https://github.com/AllToMP3/alltomp3-app/issues/142#issuecomment-576027297)
> 
> Apparently updating 'youtube-dl' binary fixes the problem (at least on Windows 10).

so... I updated the youtube dl but it still doesn't work. Was I supposed to delete the old version? I replaced it with the latest version and nothing changed.
