### ISSUE TITLE
Can't download music from Spotify

### ISSUE THREAD

**Issue by David-H-1** [AllToMP3/alltomp3-app#151]
My operating system is: Windows 10 Ver 1909
My AllToMP3 version is: 0.3.12
The song/album that I am trying to download is https://open.spotify.com/track/5zYVPAQey14E2Dqw2vrBhU (track)
or https://open.spotify.com/album/4iheJNVeRsjwypaKGNTbzJ?highlight=spotify:track:5zYVPAQey14E2Dqw2vrBhU (album)
I thought it was geo-locked so I tried a VPN server from Japan, but it still does not work
I can only abort the process and the progress bar does not even move at all even with a Japan VPN connected!
Please fix this as soon as possible
Screenshot attached.
![image](https://user-images.githubusercontent.com/60801469/75378158-10456000-5888-11ea-93c3-c08aabd1e39a.png)

**Comment by David-H-1** [comment]
@NTag Veuillez résoudre ce problème dès que possible. Merci beaucoup.

**Comment by sakshamgoyal01** [comment]
same here. trying to download https://open.spotify.com/playlist/5stQ5sxaOmcwUVFOgM3Rsv
Stuck at 0%. tried run as admin on windows but nothing

**Comment by freelog** [comment]
Same problem. Stuck at 0%. Tried also to run as admin.
No network activity during process.

**Comment by AmazingGabriel16** [comment]
> 
> 
> same here. trying to download https://open.spotify.com/playlist/5stQ5sxaOmcwUVFOgM3Rsv
> Stuck at 0%. tried run as admin on windows but nothing

I've also tried running it in admin to test this out and yes, I can confirm that it does not work.

**Comment by AnubisZ9** [comment]
Also tried downloading. Stuck at 0%. Tried building the app and same thing happens.

**Comment by sts-ryan-holton** [comment]
Same thing here, any fixes?

**Comment by sivilspg** [comment]
I can confirm this issue as well. Win10 v1909. Running as admin doesn't work. It does create "Artist/Album/" folders but the directory is empty. Left it running for a few hours with no success.

**Comment by nuganics** [comment]
I'm using Sidify and it is working.

**Comment by Eslsamu** [comment]
Not working for me either

**Comment by DerKnecht** [comment]
I have the same issue on Manjaro.

**Comment by 180207312** [comment]
Me too! The same song! And it doesn't work!

**Comment by mrjohndoe01** [comment]
Same here. :(

**Comment by NTag** [comment]
Can you try with the latest update (0.3.17)?

**Comment by sts-ryan-holton** [comment]
@NTag Tried installing the new version onto my Macbook from your website, apparently you need to update the software, it won't install, I guess certificate isn't valid.
