### ISSUE TITLE
320kbps possible? And are the tracks from the sources even native 256kbps?

### ISSUE THREAD

**Issue by WoefulWolf** [AllToMP3/alltomp3-app#163]
Just wondering if it would be possible to add an option to select maybe higher or lower bitrates.
I saw the alltomp3 library's download/convert function does have a bitrate parameter.
(I've been having some troubles getting all the dependencies and rebuilding myself)

On a similar note; is the source even natively 256kbps? If not then my above suggestion is obviously meaningless. I don't know how the ripping works exactly, but there has to be a limit of the source's bitrate.
Thanks

**Comment by armand-ferey** [comment]
@WoefulWolf  The function downloadPlaylistWithTitles will be called with the URL of the Spotify playlist, it will get the titles of all songs in the playlist through Spotify's API, and then it will search every song on YouTube with the function videoForSong.
To sum up, songs are not downloaded directly from Spotify, but from YouTube.
The quality depends on the YouTube video found, it is 128 kb/s, 192 kb/s or 256 kb/s.
The algorithm tries to find the best video, using its title, number of views, likes, dislikes, and duration. But it doesn't always find the right video.
All songs come from YouTube (or SoundCloud) at the end. And the maximum audio quality of those websites is 256 kb/s.
So there would be no gain to create 320 kb/s MP3s. Sorry :/ .

**Comment by Feuer-sturm** [comment]
Thanks for your explanation @armand-ferey . This would explain the behavior in this topic (https://github.com/AllToMP3/alltomp3-app/issues/162) where we saw that downloaded songs are different from the songs when they played in spotify.

**Comment by leon332157** [comment]
https://github.com/AllToMP3/alltomp3/blob/c131002fd714c0af0763d7c5f04bea0bb81e1df2/index.js#L1079 Don't think this is any algorithm.
