### ISSUE TITLE
Only 100 Songs per Playlist

### ISSUE THREAD

**Issue by Markus1995** [AllToMP3/alltomp3-app#17]
Hi,

i have a spotify Playlist with 770 Songs.

But AlltoMP3 shows me only 100 Songs, can you please fix it?

**Comment by egold555** [comment]
I am having this problem as well

**Comment by kipwoker** [comment]
I read the code. It seems like Spotify API response only 100 records. May be you should use limit and offset parameters instead of page? I have no possibility to test it right now, because I'm on Windows and it's hard to debug. Will be great, if you can check this idea.

**Comment by NTag** [comment]
The new version 0.3.3 released today finally handles Spotify's playlists longer than 100 items :) .

Just launch the app, and it will auto-update.
