### ISSUE TITLE
MP3 Files are not downloaded

### ISSUE THREAD

**Issue by zioproto** [AllToMP3/alltomp3-app#170]
Information
* My operating system is: MacOS El Capitan 10.11.6
* My AllToMP3 version is: 0.3.17

Passing to the application *any* Spotify Album URL, will result in the Artist and Album subfolder being created to disk, but no files downloaded.

How can I enable debug logs to see if the application gives any error ?

**Comment by LeBigFish666** [comment]
Yes same for me, No spotify linksd at all are downloading. I've sent a support request so hopefully this will be resolved soon. Issue stared about 30 hours ago for myself

**Comment by zioproto** [comment]
I tried to troubleshoot.
From the path `/Applications/AllToMP3.app/Contents/MacOS` I started the application from command line:
`./AllToMP3`

I tried to download a random album: https://open.spotify.com/album/<redacted>
```
$ ./AllToMP3
Checking for update
[DB] findOne { db: 'config', query: { name: 'saving-path' } }
{ name: 'saving-path',
  value: '/Users/ZioPRoTo/Music',
  _id: '7DSGmsIDnlJluVvT' }
{ name: 'saving-path',
  value: '/Users/ZioPRoTo/Music',
  _id: '7DSGmsIDnlJluVvT' }
[DB] findOne { db: 'config', query: { name: 'help-displayedn' } }
{ name: 'help-displayedn', value: 2, _id: 'mUi70qOTwINYqCZQ' }
Update for version 0.3.17 is not available (latest version: 0.3.17, downgrade is disallowed).
[AT3] suggestions https://open.spotify.com/album/<redacted>
[AT3] downloadPlaylist { folder: '/Users/ZioPRoTo/Music/',
  id: 'IdZNzMtyQz',
  url: 'https://open.spotify.com/album/2Tu9xNeUqunaHIaUs4DwUJ' }
[AT3] event begin-url 0
[AT3] event begin-url 1
[AT3] event begin-url 2
[AT3] event begin-url 3
```
It will just hang like this forever. The album appears with the playlist in the GUI, but the downloads seems never starting.

**Comment by zioproto** [comment]
@LeBigFish666 could you please confirm your operating system and AllToMP3 version ? thanks

**Comment by LeBigFish666** [comment]
Operationg system is Win10 and same version of the app as you, 0.3.17. I have a feeling this is from spotify's end rather than the app. I'm sure the devs will find a work around and update us. I'll commetn on this thread if I get a reply to me support request

**Comment by zioproto** [comment]
I tried to reproduce the bug today... and I can't. It works again.
@LeBigFish666 are you still able to reproduce the bug ?

**Comment by Egonpersyn** [comment]
Same problem. Is there a solution yet?

**Comment by zioproto** [comment]
@Egonpersyn some questions:
* was it working before and then it stopped working ?
* what is your operating system version ?
* is your AllToMP3 version 0.3.17 ?

thanks

**Comment by Egonpersyn** [comment]
It was working before and it stopped working yesterday.
I used it only twice.
Windows 10
and my version is the latest version of the website. alltomp3.org

Kind  regards

**Comment by LeBigFish666** [comment]
Still not working for me. I emailed for support but have had no response. I think the issue will be with the YouTube download .dl but I cant find a way to force the application to acknowledge the later version

**Comment by nerohunter9** [comment]
is there a way to fix it? I turn everything off so i could get it to work. sadly it's not working.

**Comment by ExplodingChick** [comment]
I'm facing the same issues. After it stopped working, after a week it worked again for just a day and stopped again.
I wonder if it could be the following: 

Spotify sees 4 simulatious streams while download started for a certain user account. While this is not normal for a user they could limit the number of simultanious downloads. 
What if there is an option for limiting the amount of streams to 1, could this solve the issue?

**Comment by nerohunter9** [comment]
> I'm facing the same issues. After it stopped working, after a week it worked again for just a day and stopped again.
> I wonder if it could be the following:
> 
> Spotify sees 4 simulatious streams while download started for a certain user account. While this is not normal for a user they could limit the number of simultanious downloads.
> What if there is an option for limiting the amount of streams to 1, could this solve the issue?

I hope he could fix this problem

**Comment by hchagas17** [comment]
Also having the same issue. Cannot download MP3 songs either from Spotify or Youtube.
Could use for 2 days only, now it's only hanging; folders are created but download won't start.
Tried unistalling and installing again, no luck.
Using Windows 10, AlltoMP3 verson 0.3.17

**Comment by notdodgy** [comment]
I am also having this issue - worked earlier today, now does not.

**Comment by zioproto** [comment]
Closing the github issue. No solution found. Many other users reported similar issues even with newer versions, about downloading not working. It makes no sense to keep this one open.
