### ISSUE TITLE
Ubuntu repository 404 Not found

### ISSUE THREAD

**Issue by Renaskigi6** [AllToMP3/alltomp3-app#19]
Hi, 
I tried to install the apliacion in Ubuntu. When you install it gives an error because the repository has not been found. This is what comes out when you try to do a terminal update:

`Ign:5 https://packagecloud.io/AllToMP3/alltomp3/ubuntu artful InRelease        
Err:6 https://packagecloud.io/AllToMP3/alltomp3/ubuntu artful Release
  404  Not Found [IP: 50.97.198.58 443]
Reading package lists... Done                    
E: The repository 'https://packagecloud.io/AllToMP3/alltomp3/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

I hope it is not very expensive to fix it and can install this fantastic program in Ubuntu. 
Thanks and keep it up!

**Comment by NTag** [comment]
Finally, I released a new version for Ubuntu Artful. Just do:
```
sudo apt-get update
sudo apt-get install alltomp3
```
