### ISSUE TITLE
Can not find the program in repository

### ISSUE THREAD

**Issue by Reaghaar** [AllToMP3/alltomp3-app#21]
here is the installation error:

wagner@wagner-H14CU01 ~ $ sudo pip install pathlib
[sudo] senha para wagner: 
The directory '/home/wagner/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/wagner/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pathlib in /usr/local/lib/python2.7/dist-packages
wagner@wagner-H14CU01 ~ $ curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash
Detected operating system as LinuxMint/sylvia.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
wagner@wagner-H14CU01 ~ $ sudo apt-get install alltomp3
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
E: Impossível encontrar o pacote alltomp3
wagner@wagner-H14CU01 ~ $

**Comment by NTag** [comment]
Finally, I released a new version for LinuxMint Sylvia. Just do:
```
sudo apt-get update
sudo apt-get install alltomp3
```
