### ISSUE TITLE
soundcloud new tracks, other audio downloaded but blank(muted) audio

### ISSUE THREAD

**Issue by wolfbunnies** [AllToMP3/alltomp3-app#22]
i always trusted all2mp3 in the past because of the reliability of downloading non-mainstream tracks and with it their album art but it seems these days whenever i enter in the links that i really need, it just gets stuck without any progress on them besides the abort. please get it fixed, i waited so long for the app but now it seems i can't rely it as much when it was a website working page. :(

**Comment by wolfbunnies** [comment]
![screenshot 5](https://user-images.githubusercontent.com/28444843/36182460-b4422fb6-1164-11e8-994e-9836f078f093.png)
 above is an example

**Comment by wolfbunnies** [comment]
![screenshot 3](https://user-images.githubusercontent.com/28444843/36182490-d8f5d510-1164-11e8-9718-519c593d6b67.png)
above is an example

**Comment by NTag** [comment]
Indeed, SoundCloud downloads were broken. The new version 0.3.3 released today should fix it! Just open the app and it will auto-update :) .

**Comment by ShadowJonathan** [comment]
As of today, i seem to have the same problem with 0.3.4
![](https://i.imgur.com/4mMEdGa.png)
Not sure if this is an issue with me, or if *nobody* can download soundcloud
