### ISSUE TITLE
E: Unable to locate package alltomp3

### ISSUE THREAD

**Issue by AceThaGemini** [AllToMP3/alltomp3-app#23]
Hey good people! Uh.. It's that Mint 18.2 user here :wave:  
`sudo pip install pathlib` worked fine :white_check_mark: 
`curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash` Like charm :white_check_mark: 
But when I try `sudo apt install alltomp3` I get this heartbreaking response `E: Unable to locate package alltomp3`
![screenshot from 2018-02-16 11-12-56](https://user-images.githubusercontent.com/18669218/36298697-6ef0c222-130a-11e8-855b-30335a581cf7.png)

**Comment by AceThaGemini** [comment]
Tried `sudo apt update` and seems like `apt-secure` is disabling the repo.
There's this message:
`Err:26 https://packagecloud.io/AllToMP3/alltomp3/linuxmint sonya Release`
`404  Not Found`
`E: The repository 'https://packagecloud.io/AllToMP3/alltomp3/linuxmint sonya Release' does not have a Release file.`
`N: Updating from such a repository can't be done securely, and is therefore disabled by default.`

**Comment by NTag** [comment]
I just released a new version for LinuxMint Sonya. Just do:
```
sudo apt-get update
sudo apt-get install alltomp3
```

**Comment by peterlymo** [comment]
Err:17 https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic Release        
  404  Not Found [IP: 50.97.198.58 443]

**Comment by TwistedPrime** [comment]
twisted@twisted-desktop:~$ curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash
Detected operating system as Ubuntu/disco.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
twisted@twisted-desktop:~$ sudo apt-get install alltomp3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package alltomp3

**Comment by Fthi-S3074641** [comment]
same problem is happening in
operating system LinuxMint/tina.
