### ISSUE TITLE
Max 100 songs

### ISSUE THREAD

**Issue by BillyHu99** [AllToMP3/alltomp3-app#6]
The app only downloads 100 songs at most when entering a playlist with 100+ songs.

**Comment by ArthurAssuncao** [comment]
I think, this is a limit from spotify API which return 100 in 100 tracks, the correction could be done in AllToMP3 server.
Sample:
PlaylistURL/tracks?offset=0&limit=100&market=from_token
PlaylistURL/tracks?offset=100&limit=100&market=from_token

**Comment by Ossobuko** [comment]
Creating a second playlist containing the songs that are after the 100th and downloading that playlist too might be a acceptable workaround.

**Comment by NTag** [comment]
Fixed with https://github.com/AllToMP3/alltomp3/commit/19ff521e5877d5ff40c9b8f16d023ae645acb91b.

It will be available in the next release ;) .
