### ISSUE TITLE
Doesn't work anymore? (Solved)

### ISSUE THREAD

**Issue by IvoryOwl92** [AllToMP3/alltomp3-app#67]
I tried several Spotify songs and a few others from YouTube. I put the link in, it downloads and 'finishes' but the songs don't show up in the folder. Does the app still work or is it a problem on my end?

**Comment by IvoryOwl92** [comment]
I managed to track down the culprit - it was Malwarebytes.
I turned off real-time protection and all files I had previously downloaded finally showed up in the folder.
I tried to make exceptions for it, both .exe and folder but somehow it doesn't work so I guess whenever I wish to download a few songs I better turn it off temporarily.

**Comment by Amirhf1** [comment]
Installer problem in Ubuntu 18

**Comment by XzipbitA** [comment]
It's important that the application has rights to the download location.
Try running the app by right-clicking the icon and running it as administrator.

**Comment by ce1246** [comment]
when i tried pasting links from Spotify it won't download.

**Comment by nerohunter9** [comment]
> when i tried pasting links from Spotify it won't download.

same, it was working yesterday when i download a playlist that contain 50 songs and 10 albums.

**Comment by ce1246** [comment]
uhm i don't know but finally it worked again. it worked the other day then
didn't work the day after and now it's working again

**Comment by davidcarmo23** [comment]
Downloaded the app today and it doesn't start the download doesnt matter if its a playlist or a single song

**Comment by szymon420699** [comment]
bruh this was made 3 years ago and spotify playlist songs anything dont work on windows

**Comment by pupshadow** [comment]
This is still an issue please reopen.

**Comment by thompson8964** [comment]
I also have this issue

**Comment by HoseinGhanbari** [comment]
same here ... 
playlist name and items gets fetched successfully but no file download gets started.
