### ISSUE TITLE
Just a blank screen after app is opened.

### ISSUE THREAD

**Issue by ajaymathew522** [AllToMP3/alltomp3-app#68]
I recently installed the software version 0.3.4 on 11th August.And I
 did add an exception to the software in windows defender.But no matter what I do,all I get is a blank white screen.Any remedies for this??????
![screenshot 19](https://user-images.githubusercontent.com/37475882/43995186-3252d808-9dc7-11e8-8509-ea7167dfb011.png)

**Comment by NTag** [comment]
It's strange; can you try to download it again from the website and reinstall it? The first installation my have failed somewhere.
