### ISSUE TITLE
Spotify playlists won't download

### ISSUE THREAD

**Issue by wrybread** [AllToMP3/alltomp3-app#71]
I can't download more than 9 songs of any Spotify playlist. This one for example:

https://open.spotify.com/user/1291749220/playlist/7zvyvzZcsLZi89DAxgVxav?si=1F04Yu3MQ6KkBhd_WJNJNA

It gets to 9 songs (not in the correct order) and stops downloading. 

Another playlist to test with:

https://open.spotify.com/user/1291749220/playlist/56Iao390W5mOZZWEpWiuP0?si=gA6Ds9STRpGEKxId8wK52A

I'm on Windows 7. Let me know if you need any more info, and glad to test any fixes.

**Comment by NaitChris** [comment]
The App is also not crawling the Playlist Infos. 
![alltomp3](https://user-images.githubusercontent.com/12734861/44460114-3bece780-a60c-11e8-9a7c-abf1cf6c2799.PNG)
After 1 Hour, no donwload or Infos of the Playlist.

**Comment by wrybread** [comment]
Strange, it does obtain my playlist info, but never gets further than 7 to 9 songs downloaded.

![screenshot](https://user-images.githubusercontent.com/10524548/44474758-45645880-a5e8-11e8-8f8b-1fab1ddfddff.jpg)

Interestingly I had the same issue months ago and posted about it, but the issue was marked fixed.

https://github.com/AllToMP3/alltomp3/issues/10#issuecomment-352253032

**Comment by NaitChris** [comment]
This is realy strange, right.
I have downloaded the lastest Version, but my Playlist details was not crawled.

**Comment by wrybread** [comment]
> Edit2: Comand back, the download works now after a little waiting time. The playlist with 57 Tracks was completely downloaded.

Hmm. Is it working for this playlist? That should have a length of 164 songs:

https://open.spotify.com/user/1291749220/playlist/7zvyvzZcsLZi89DAxgVxav?si=1F04Yu3MQ6KkBhd_WJNJNA

**Comment by cmario92** [comment]
Same with me, can not download a spotify playlist that includes more than 9 songs. It does not even download a single song

**Comment by NTag** [comment]
Can you try again with the latest version (0.3.6)?

If it still doesn't work, re-open the issue and say the exact Spotify URL you used.

**Comment by wrybread** [comment]
Still having the issue with version 0.3.6. This is the exact Spotify URL I'm using:

https://open.spotify.com/user/1291749220/playlist/7zvyvzZcsLZi89DAxgVxav?si=1F04Yu3MQ6KkBhd_WJNJNA

It downloads 8 songs and then freezes.

I'm on Windows 7 if that's a factor.

**Comment by g8f6r4e7x2** [comment]
Still having problems with Spotify playlists on 0.3.8
This is the playlist https://open.spotify.com/user/spotify/playlist/37i9dQZF1DWZqUHC2tviPw?si=6XCeq_61TJO-EIV4x7P6-w
