### ISSUE TITLE
not working download from Spotify on latest release

### ISSUE THREAD

**Issue by steph9009** [AllToMP3/alltomp3-app#72]
two big problems:

1. program won't show single track loading, even if downloaded (file is present in folder). It just stays black with no info.
2. program won't download entire albums, even if some songs are shown as completed (they remain grey and won't turn white). (no files in folder for this.)

i have Windows 10. Ok, this is a third problem. Whatever.

**Comment by steph9009** [comment]
oh, I try the same album with previous version, perfectly working.

But previous version continuously download update in background and f*cks all up.

**Comment by NTag** [comment]
I released a new version (0.3.6) which should fix the regression. Feel free to re-open the issue if the problem stays!
