### ISSUE TITLE
Download isn't really working...at all.

### ISSUE THREAD

**Issue by SuperNunb** [AllToMP3/alltomp3-app#83]
* My operating system is: [Windows];
* My AllToMP3 version is: [0.3.6]; I believe
I had used this program before on a different computer, and it worked just fine. I replaced my computer and now every song I add to the download queue only fills the progress circle about 1% of the way. I've tried both Spotify and YouTube.
Here's a track I've tried:
https://www.youtube.com/watch?v=MhVOsXVLo54
![image](https://user-images.githubusercontent.com/33640719/47262112-ebc3c180-d4a4-11e8-8798-49eb044ebacd.png)

**Comment by sniper85500** [comment]
same here. Windows 7 V0.3.6. 
Tried to download https://open.spotify.com/playlist/6RMoIh0N6NPokXLKV6AyUX

**Comment by Ar1sC** [comment]
Same, Windows 10, 1803

**Comment by mxdpeep** [comment]
correct, not working at all

**Comment by germanafro** [comment]
likely related to #89 

btw there are like 5 issues open on this topic already. why do you all make separate issues for this?

**Comment by mxdpeep** [comment]
really???

general.minggy service blocked by anti malware software

how is it related to non-working download?


s pozdravem,

*Filip Oščádal*
*fredbrooker.gscloud.cz <https://fredbrooker.gscloud.cz>*

**Comment by germanafro** [comment]
my bad. this one might be something else. 

blocking minggy just prevents creating the mp3 after the download is finished

**Comment by lucashussey** [comment]
Are you still experiencing this issue? I was having the same problem. Try re-selecting your download folder in AlltoMP3. If your old download folder has been moved/deleted, AlltoMP3 can't find the folder so it doesn't download anything.
