### ISSUE TITLE
E: Unable to locate package alltomp3  - Mint 19 Tara

### ISSUE THREAD

**Issue by wiwi936** [AllToMP3/alltomp3-app#97]
Hi, 
doesn't work on mint19 Tara even after system update

===>>  curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash
Detected operating system as LinuxMint/tara.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
===>> sudo apt-get install alltomp3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package alltomp3

**Comment by marcelofranzen** [comment]
Same issue in Kubuntu 18.10.

**Comment by tiago4171** [comment]
Well, I have a workarround and I'ts pretty easy to execute.
Follow the steps and remember: This will only work in Ubuntu 18.04 and above(The *buntu's 18.04 and above based should work too)!!

1 - $ cd /tmp/
2 - $ curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh >> alltomp3.sh
3 - $ chmod +x alltomp3.sh
4 - $ sudo os=ubuntu dist=bionic ./alltomp3.sh
5 - $ sudo apt install alltomp3

**Comment by wiwi936** [comment]
It works right now!
Thank you very much!
